config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Users', 'action' => 'login']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    // $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */
Router::scope('/articles', function (RouteBuilder $routes) {
    $routes->connect('/tagged/*', ['controller' => 'Articles', 'action' => 'tags']);
});

src/Model/Table/PostsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

class PostsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('posts');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Users')
            ->setForeignKey('user_id');

        $this->hasMany('PostLikes')
            ->setForeignKey('post_id');

        $this->hasMany('PostComments')
            ->setForeignKey('post_id');

        $this->hasMany('Reposts')
            ->setForeignKey('parent_id');

        $this->belongsTo('Reposts', ['className' => 'Posts'])
            ->setForeignKey('parent_id');
    }

    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('user_id')
            ->notEmptyString('user_id', 'Invalid action. Cannot access session user id.');

        $validator
            ->requirePresence('content')
            ->maxLength('content', 140)
            ->notEmptyString('content', 'Post content is required');


        $validator
            ->allowEmptyFile('image_name')
            ->add('image_name', 'validExtension', [
                'rule' => ['extension', ['png', 'jpg', 'gif', 'jpeg']], 
                'message' => 'Please supply a valid image. 
                    Allowed extensions are only gif, jpeg, png and jpg.'
            ]);

        return $validator;
    }
}

src/Controller/SearchesController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;
use Cake\Event\Event;

/**
* Searches Controller
*
*/
class SearchesController extends AppController 
{

    public function initialize()
    {
        parent::initialize();
        $this->loadComponent('Paginator');
    }

    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event);
    }
    
    /**
    * Index method
    *
    * This method display the search results based on selected type and keyword.
    * This can either displays users or posts.
    *
    * @return \Cake\Http\Response|null
    */
    public function index() 
    {
        $type = '';
        $keyword = '';
        $data = $this->getCleanData();

        if (isset($data['type'])) {
            $type = $data['type'];
            $this->getRequest()->getSession()->delete('SearchKeyword');
        } else {
            if($this->getRequest()->getSession()->check('SearchType')) {
                $type = $this->getRequest()->getSession()->read('SearchType');
            } else {
                $type = 'user';
            }
        }
        if (isset($data['keyword'])) {
            $keyword = $data['keyword'];
        } else {
            if($this->getRequest()->getSession()->check('SearchKeyword')) {
                $keyword = $this->getRequest()->getSession()->read('SearchKeyword');
            }
        }

        $this->getRequest()->getSession()->write('SearchType', $type);
        $this->getRequest()->getSession()->write('SearchKeyword', $keyword);

        $this->set(compact('keyword'));

        if ($type == 'post') {
            $renderForm = 'posts';
            $posts = $this->getPostList($keyword);
            $comments = $this->getPostComments($posts);

            $this->set(compact('comments'));
            $this->set(compact('posts'));
        } else {
            $renderForm = 'users';
            $users = $this->getUsersList($keyword);
            $followed = $this->checkUsersFollowing($users);

            $this->set(compact('followed'));
            $this->set(compact('users'));
        }
        
        $this->render($renderForm);
    }

    /**
    * Get Users List method
    *
    * This method returns the list of active users depending on the provided keyword filter.
    *
    * @param string $keyword Name of the users
    *
    * @return object
    */
    private function getUsersList(string $keyword) : object
    {
        $user = TableRegistry::getTableLocator()->get('Users');
        $this->paginate = [
            'conditions' => [
                'activated' => 1,
                'OR' => [
                    ["CONCAT(first_name,' ',last_name) LIKE" => "%{$keyword}%"],
                    ['username LIKE' => "%{$keyword}%"]
                ]
            ],
            'limit' => 10,
            'order' => ['Posts.created' => 'desc']  
        ];
        $users = $this->paginate($user);

        return $users;
    }

    /**
    * Check User Following method
    *
    * This method checks if the specifid user has been followed by the currently logged in user.
    *
    * @param object $users
    *
    * @return array
    */
    private function checkUsersFollowing(object $users) : array
    {
        $followed = [];
        $sessUid = $this->Auth->User('id');
        
        foreach ($users as $key => $user) {
            $followed[$key] = $this->checkFollowing($user->id, $sessUid);
        }

        return $followed;
    }

    /**
    * Check Following method
    *
    * This method checks if the viewed user has been followed by the currently logged in user.
    *
    * @param int $userId User id
    * @param int $sessUid User id of the currently logged in account
    *
    * @return bool
    */
    private function checkFollowing(int $userId, int $sessUid) : bool
    {

        $follows = TableRegistry::getTableLocator()->get('Follows');
        $query = $follows->findAllByFollowed_idAndFollower_id($userId, $sessUid);
        $result = $query->toArray();

        $return = ($result) ? true : false;

        return $return;
    }

    /**
    * Get Posts List method
    *
    * This method returns the list of active posts depending on the provided keyword filter.
    *
    * @param string $keyword Contents of the post
    *
    * @return object
    */
    private function getPostList(string $keyword) : object
    {
        $post = TableRegistry::getTableLocator()->get('Posts');
        $this->paginate = [
            'contain' => ['Users', 'Reposts.Users'],
            'conditions' => [
                'Posts.content LIKE' => "%{$keyword}%",
                'Posts.deleted' => 0,
            ],
            'limit' => 10,
            'order' => ['Posts.created' => 'desc']  
        ];
        $posts = $this->paginate($post);

        return $posts;
    }

    /**
    * Get PostComments method
    *
    * This method fetches and builds each post's comments.
    *
    * @param object $posts User's posts dataset
    *
    * @return array
    */
    private function getPostComments(object $posts) : array
    {
        $comments = [];
        $sessUid = $this->Auth->User('id');
        foreach ($posts as $key => $post) {
            $postId = $post['id'];

            $PostComments = TableRegistry::getTableLocator()->get('PostComments');
            $comments[$key]['comments'] = $PostComments->find()
                ->where([
                    'PostComments.post_id' => $postId,
                    'PostComments.deleted' => 0
                ])
                ->contain('Users')
                ->toArray();
            $PostComments = TableRegistry::getTableLocator()->get('PostComments');
            $comments[$key]['commentCount'] = $PostComments->find()
                ->where([
                    'post_id' => $postId,
                    'deleted' => 0
                ])
                ->count();

            $PostLikes = TableRegistry::getTableLocator()->get('PostLikes');
            $comments[$key]['likeCount'] = $PostLikes->find()
                ->where(['post_id' => $postId])
                ->count();

            $PostLikes = TableRegistry::getTableLocator()->get('PostLikes');
            $result = $PostLikes->findByPost_idAndUser_id($postId, $sessUid)
                ->first();
            $comments[$key]['userLiked'] = ($result) ? true : false;

        }

        return $comments;
    }

}

src/Template/Searches/posts.ctp
<div class="row p-5">
    <div class="col-sm-12 col-lg-2"></div>
    <div class="col-sm-12 col-lg-8 ">
        <div class="container shadow-lg bg-transparent mt-2 py-2">
            <h5>Search Results
                <span class="badge badge-light ml-2">
                    <?= $this->Paginator->params()['count'] ?>
                </span>
                <h6 class="d-inline">
                    Search Type :
                    <span class="badge badge-primary font-weight-light ml-2"> 
                        &nbsp;Posts&nbsp;
                    </span>
                </h6> 
                <h6 class="d-inline ml-3">
                    Keyword :
                    <span class="badge badge-primary font-weight-light ml-2">
                        &nbsp;<?= h($keyword) ?>&nbsp;
                    </span>
                </h6> 
            </h5>
            <hr>
            <div class="row">
                <div class="col-sm-12" >
                    <?php if ($posts): ?>
                    <?php foreach ($posts as $key => $post): ?>
                    <div class="card mb-3">
                        <?= $this->element('posts/post_view',['post' => $post]) ?>
                        <!-- REPOST CONTAINER -->
                        <?php if(isset($post->repost->id)): ?>
                        <?= $this->element('posts/repost_view',['post' => $post]) ?>
                        <?php endif ?>
                        <?= $this->element('posts/comments',[
                            'comment' => $comments[$key],
                            'post' => $post
                        ]) ?>
                    </div>
                    <?php endforeach ?>
                    <?= $this->element('common/pagination') ?>
                    <?php else: ?>
                        <h6 class="text-center">No results found.</h6>
                    <?php endif ?>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-lg-2"></div>
</div>
<?= $this->element('posts/edit_post') ?>
<?= $this->element('posts/repost') ?>
<?= $this->element('posts/edit_comment') ?>

<?= $this->Html->script('search') ?>
<?= $this->Html->script('post') ?>

src/Template/Searches/users.ctp
<div class="row p-5">
    <div class="col-sm-12 col-lg-3"></div>
    <div class="col-sm-12 col-lg-6 ">
        <div class="container shadow-lg bg-transparent mt-2 py-2">
            <h5>Search Results
                <span class="badge badge-light ml-2">
                    <?= $this->Paginator->params()['count'] ?>
                </span>
                <h6 class="d-inline">
                    Search Type :
                    <span class="badge badge-primary font-weight-light ml-2"> 
                        &nbsp;Users&nbsp;
                    </span>
                </h6> 
                <h6 class="d-inline ml-3">
                    Keyword :
                    <span class="badge badge-primary font-weight-light ml-2">
                        &nbsp;<?= h($keyword) ?>&nbsp;
                    </span>
                </h6> 
            </h5>
            <hr>
            <div class="row">
                <div class="col-sm-12" >
                    <?php if ($users): ?>
                    <?php foreach ($users as $key => $user): ?>
                    <div class="card">
                        <div class="card-body py-2">
                            <?php 
                                if($user->profile_picture) {
                                    $profile = $user->profile_picture;
                                } else {
                                    $profile = 'default-profile.png';
                                }
                            ?>
                            <?= $this->Html->image(
                                'profiles/'.$profile, 
                                ['alt' => '',
                                    'class' => 'rounded-circle d-inline-block',
                                    'width' => '50',
                                    'height' => '50'
                                ]
                            ) ?>
                            <div class="d-inline-block align-bottom pl-2">
                                <h6 class="font-weight-bold m-0 route-user"
                                    data-userId="<?= $user->id ?>">
                                    <?= $user->first_name ?> 
                                    <?= $user->last_name ?>
                                </h6>
                                <h6 class="small font-italic text-muted">
                                    @<?= $user->username ?>
                                </h6>
                            </div>
                            <?php 
                                if ($user->id == $authUser['id']) {
                                    $displayClass = 'd-none';
                                } else {
                                    $displayClass = 'd-inline-block';
                                }
                            ?>
                            <div class="<?= $displayClass ?> align-middle float-right line-hieght-50">
                                <?php 
                                    if ($followed[$key]) {
                                        $followLabel = 'Unfollow';
                                        $class = 'btn-secondary px-2';
                                    } else {
                                        $followLabel = 'Follow';
                                        $class = 'btn-outline-secondary px-3';
                                    }
                                ?>
                                <?= $this->Form->postButton(
                                    $followLabel,
                                    [
                                        'controller' => 'follows',
                                        'action' => 'follow',
                                        $user->id
                                    ],
                                    ['class' => "btn btn-sm {$class}"]
                                ) ?>
                            </div>
                        </div>
                    </div>
                    <?php endforeach;?>
                    <?= $this->element('common/pagination') ?>
                    <?php else: ?>
                        <h6 class="text-center">No results found.</h6>
                    <?php endif ?>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-lg-3"></div>
</div>
<?= $this->Html->script('search') ?>